# Generated by Django 4.2.11 on 2024-04-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PangeaServiceModel',
            fields=[
                ('pid', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('pid', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_added', models.CharField(blank=True, max_length=20, null=True)),
                ('is_pin_set', models.BooleanField(default=False)),
                ('pin', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PangeaSecurityModel',
            fields=[
                ('pid', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('pangea_services', models.ManyToManyField(blank=True, to='myapp.pangeaservicemodel')),
            ],
        ),
    ]
