# Generated by Django 4.2.11 on 2024-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseModel',
            fields=[
                ('did', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(blank=True, choices=[('aws', 'AWS')], max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('mongoDB', 'MongoDB')], max_length=255, null=True)),
            ],
        ),
    ]
