# Generated by Django 4.2.11 on 2024-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_databasemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasemodel',
            old_name='did',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('running', 'running'), ('inactive', 'inactive'), ('error', 'error')], default='inactive', max_length=255, null=True),
        ),
    ]
