# Generated by Django 4.2.11 on 2024-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_did_databasemodel_pid_databasemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemodel',
            name='provider',
        ),
        migrations.AddField(
            model_name='databasemodel',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
