# Generated by Django 4.2.11 on 2024-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_databasemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('pid', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('sharable_link', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='storage_files/')),
            ],
        ),
    ]
