# Generated by Django 4.2.11 on 2024-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_prediction_storagemodel_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
