# Generated by Django 4.2.11 on 2024-04-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_storagemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('api_id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('flow_id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('nodes', models.JSONField(blank=True, null=True)),
                ('edges', models.JSONField(blank=True, null=True)),
                ('developement_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='card_added',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_pin_set',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pin',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('pid', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ManyToManyField(blank=True, to='myapp.apimodel')),
                ('database', models.ManyToManyField(blank=True, to='myapp.databasemodel')),
                ('pangea_security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pangeasecuritymodel')),
                ('storages', models.ManyToManyField(blank=True, to='myapp.storagemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='apimodel',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.flowmodel'),
        ),
    ]
